/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGAirport.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGAirport::SWGAirport(QString* json) {
    init();
    this->fromJson(*json);
}

SWGAirport::SWGAirport() {
    init();
}

SWGAirport::~SWGAirport() {
    this->cleanup();
}

void
SWGAirport::init() {
    airport = new QString("");
terminal = new QString("");
}

void
SWGAirport::cleanup() {
    if(airport != NULL) {
        delete airport;
    }
if(terminal != NULL) {
        delete terminal;
    }
}

SWGAirport*
SWGAirport::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGAirport::fromJsonObject(QJsonObject &pJson) {
    setValue(&airport, pJson["airport"], "QString", "QString");
setValue(&terminal, pJson["terminal"], "QString", "QString");
}

QString
SWGAirport::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGAirport::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("airport"), airport, obj, QString("QString"));
    
        

    
    toJsonValue(QString("terminal"), terminal, obj, QString("QString"));
    
        

    return obj;
}

QString*
SWGAirport::getAirport() {
    return airport;
}
void
SWGAirport::setAirport(QString* airport) {
    this->airport = airport;
}

QString*
SWGAirport::getTerminal() {
    return terminal;
}
void
SWGAirport::setTerminal(QString* terminal) {
    this->terminal = terminal;
}



} /* namespace Swagger */

