/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGAffiliateSearchResponse.h
 * 
 * 
 */

#ifndef SWGAffiliateSearchResponse_H_
#define SWGAffiliateSearchResponse_H_

#include <QJsonObject>


#include "SWGAffiliateSearchMeta.h"
#include "SWGAffiliateSearchResult.h"
#include <QList>

#include "SWGObject.h"


namespace Swagger {

class SWGAffiliateSearchResponse: public SWGObject {
public:
    SWGAffiliateSearchResponse();
    SWGAffiliateSearchResponse(QString* json);
    virtual ~SWGAffiliateSearchResponse();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGAffiliateSearchResponse* fromJson(QString &jsonString);

    SWGAffiliateSearchMeta* getMeta();
    void setMeta(SWGAffiliateSearchMeta* meta);
QList<SWGAffiliateSearchResult*>* getResults();
    void setResults(QList<SWGAffiliateSearchResult*>* results);

private:
    SWGAffiliateSearchMeta* meta;
QList<SWGAffiliateSearchResult*>* results;
};

} /* namespace Swagger */

#endif /* SWGAffiliateSearchResponse_H_ */
