/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGAffiliateSearchResponse.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGAffiliateSearchResponse::SWGAffiliateSearchResponse(QString* json) {
    init();
    this->fromJson(*json);
}

SWGAffiliateSearchResponse::SWGAffiliateSearchResponse() {
    init();
}

SWGAffiliateSearchResponse::~SWGAffiliateSearchResponse() {
    this->cleanup();
}

void
SWGAffiliateSearchResponse::init() {
    meta = new SWGAffiliateSearchMeta();
results = new QList<SWGAffiliateSearchResult*>();
}

void
SWGAffiliateSearchResponse::cleanup() {
    if(meta != NULL) {
        delete meta;
    }
if(results != NULL) {
        QList<SWGAffiliateSearchResult*>* arr = results;
        foreach(SWGAffiliateSearchResult* o, *arr) {
            delete o;
        }
        delete results;
    }
}

SWGAffiliateSearchResponse*
SWGAffiliateSearchResponse::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGAffiliateSearchResponse::fromJsonObject(QJsonObject &pJson) {
    setValue(&meta, pJson["meta"], "SWGAffiliateSearchMeta", "SWGAffiliateSearchMeta");
setValue(&results, pJson["results"], "QList", "SWGAffiliateSearchResult");
}

QString
SWGAffiliateSearchResponse::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGAffiliateSearchResponse::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("meta"), meta, obj, QString("SWGAffiliateSearchMeta"));
    
        

    
    QList<SWGAffiliateSearchResult*>* resultsList = results;
    QJsonArray resultsJsonArray;
    toJsonArray((QList<void*>*)results, &resultsJsonArray, "results", "SWGAffiliateSearchResult");

    obj->insert("results", resultsJsonArray);
    

    return obj;
}

SWGAffiliateSearchMeta*
SWGAffiliateSearchResponse::getMeta() {
    return meta;
}
void
SWGAffiliateSearchResponse::setMeta(SWGAffiliateSearchMeta* meta) {
    this->meta = meta;
}

QList<SWGAffiliateSearchResult*>*
SWGAffiliateSearchResponse::getResults() {
    return results;
}
void
SWGAffiliateSearchResponse::setResults(QList<SWGAffiliateSearchResult*>* results) {
    this->results = results;
}



} /* namespace Swagger */

