/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGAirportAutocompleteResponse.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGAirportAutocompleteResponse::SWGAirportAutocompleteResponse(QString* json) {
    init();
    this->fromJson(*json);
}

SWGAirportAutocompleteResponse::SWGAirportAutocompleteResponse() {
    init();
}

SWGAirportAutocompleteResponse::~SWGAirportAutocompleteResponse() {
    this->cleanup();
}

void
SWGAirportAutocompleteResponse::init() {
    value = new QString("");
label = new QString("");
}

void
SWGAirportAutocompleteResponse::cleanup() {
    if(value != NULL) {
        delete value;
    }
if(label != NULL) {
        delete label;
    }
}

SWGAirportAutocompleteResponse*
SWGAirportAutocompleteResponse::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGAirportAutocompleteResponse::fromJsonObject(QJsonObject &pJson) {
    setValue(&value, pJson["value"], "QString", "QString");
setValue(&label, pJson["label"], "QString", "QString");
}

QString
SWGAirportAutocompleteResponse::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGAirportAutocompleteResponse::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("value"), value, obj, QString("QString"));
    
        

    
    toJsonValue(QString("label"), label, obj, QString("QString"));
    
        

    return obj;
}

QString*
SWGAirportAutocompleteResponse::getValue() {
    return value;
}
void
SWGAirportAutocompleteResponse::setValue(QString* value) {
    this->value = value;
}

QString*
SWGAirportAutocompleteResponse::getLabel() {
    return label;
}
void
SWGAirportAutocompleteResponse::setLabel(QString* label) {
    this->label = label;
}



} /* namespace Swagger */

