/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGAirportInformation.h
 * 
 * 
 */

#ifndef SWGAirportInformation_H_
#define SWGAirportInformation_H_

#include <QJsonObject>


#include "SWGGeolocation.h"
#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGAirportInformation: public SWGObject {
public:
    SWGAirportInformation();
    SWGAirportInformation(QString* json);
    virtual ~SWGAirportInformation();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGAirportInformation* fromJson(QString &jsonString);

    QString* getCode();
    void setCode(QString* code);
QString* getName();
    void setName(QString* name);
QString* getCityCode();
    void setCityCode(QString* city_code);
QString* getCityName();
    void setCityName(QString* city_name);
QString* getState();
    void setState(QString* state);
QString* getCountry();
    void setCountry(QString* country);
SWGGeolocation* getLocation();
    void setLocation(SWGGeolocation* location);
qint32 getAircraftMovements();
    void setAircraftMovements(qint32 aircraft_movements);
QString* getTimezone();
    void setTimezone(QString* timezone);

private:
    QString* code;
QString* name;
QString* city_code;
QString* city_name;
QString* state;
QString* country;
SWGGeolocation* location;
qint32 aircraft_movements;
QString* timezone;
};

} /* namespace Swagger */

#endif /* SWGAirportInformation_H_ */
