/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGAirportInformation.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGAirportInformation::SWGAirportInformation(QString* json) {
    init();
    this->fromJson(*json);
}

SWGAirportInformation::SWGAirportInformation() {
    init();
}

SWGAirportInformation::~SWGAirportInformation() {
    this->cleanup();
}

void
SWGAirportInformation::init() {
    code = new QString("");
name = new QString("");
city_code = new QString("");
city_name = new QString("");
state = new QString("");
country = new QString("");
location = new SWGGeolocation();
aircraft_movements = NULL;
timezone = new QString("");
}

void
SWGAirportInformation::cleanup() {
    if(code != NULL) {
        delete code;
    }
if(name != NULL) {
        delete name;
    }
if(city_code != NULL) {
        delete city_code;
    }
if(city_name != NULL) {
        delete city_name;
    }
if(state != NULL) {
        delete state;
    }
if(country != NULL) {
        delete country;
    }
if(location != NULL) {
        delete location;
    }

if(timezone != NULL) {
        delete timezone;
    }
}

SWGAirportInformation*
SWGAirportInformation::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGAirportInformation::fromJsonObject(QJsonObject &pJson) {
    setValue(&code, pJson["code"], "QString", "QString");
setValue(&name, pJson["name"], "QString", "QString");
setValue(&city_code, pJson["city_code"], "QString", "QString");
setValue(&city_name, pJson["city_name"], "QString", "QString");
setValue(&state, pJson["state"], "QString", "QString");
setValue(&country, pJson["country"], "QString", "QString");
setValue(&location, pJson["location"], "SWGGeolocation", "SWGGeolocation");
setValue(&aircraft_movements, pJson["aircraft_movements"], "qint32", "");
setValue(&timezone, pJson["timezone"], "QString", "QString");
}

QString
SWGAirportInformation::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGAirportInformation::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("code"), code, obj, QString("QString"));
    
        

    
    toJsonValue(QString("name"), name, obj, QString("QString"));
    
        

    
    toJsonValue(QString("city_code"), city_code, obj, QString("QString"));
    
        

    
    toJsonValue(QString("city_name"), city_name, obj, QString("QString"));
    
        

    
    toJsonValue(QString("state"), state, obj, QString("QString"));
    
        

    
    toJsonValue(QString("country"), country, obj, QString("QString"));
    
        

    
    toJsonValue(QString("location"), location, obj, QString("SWGGeolocation"));
    
        
obj->insert("aircraft_movements", QJsonValue(aircraft_movements));

    
    toJsonValue(QString("timezone"), timezone, obj, QString("QString"));
    
        

    return obj;
}

QString*
SWGAirportInformation::getCode() {
    return code;
}
void
SWGAirportInformation::setCode(QString* code) {
    this->code = code;
}

QString*
SWGAirportInformation::getName() {
    return name;
}
void
SWGAirportInformation::setName(QString* name) {
    this->name = name;
}

QString*
SWGAirportInformation::getCityCode() {
    return city_code;
}
void
SWGAirportInformation::setCityCode(QString* city_code) {
    this->city_code = city_code;
}

QString*
SWGAirportInformation::getCityName() {
    return city_name;
}
void
SWGAirportInformation::setCityName(QString* city_name) {
    this->city_name = city_name;
}

QString*
SWGAirportInformation::getState() {
    return state;
}
void
SWGAirportInformation::setState(QString* state) {
    this->state = state;
}

QString*
SWGAirportInformation::getCountry() {
    return country;
}
void
SWGAirportInformation::setCountry(QString* country) {
    this->country = country;
}

SWGGeolocation*
SWGAirportInformation::getLocation() {
    return location;
}
void
SWGAirportInformation::setLocation(SWGGeolocation* location) {
    this->location = location;
}

qint32
SWGAirportInformation::getAircraftMovements() {
    return aircraft_movements;
}
void
SWGAirportInformation::setAircraftMovements(qint32 aircraft_movements) {
    this->aircraft_movements = aircraft_movements;
}

QString*
SWGAirportInformation::getTimezone() {
    return timezone;
}
void
SWGAirportInformation::setTimezone(QString* timezone) {
    this->timezone = timezone;
}



} /* namespace Swagger */

