/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGAward.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGAward::SWGAward(QString* json) {
    init();
    this->fromJson(*json);
}

SWGAward::SWGAward() {
    init();
}

SWGAward::~SWGAward() {
    this->cleanup();
}

void
SWGAward::init() {
    provider = new QString("");
rating = new QString("");
}

void
SWGAward::cleanup() {
    if(provider != NULL) {
        delete provider;
    }
if(rating != NULL) {
        delete rating;
    }
}

SWGAward*
SWGAward::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGAward::fromJsonObject(QJsonObject &pJson) {
    setValue(&provider, pJson["provider"], "QString", "QString");
setValue(&rating, pJson["rating"], "QString", "QString");
}

QString
SWGAward::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGAward::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("provider"), provider, obj, QString("QString"));
    
        

    
    toJsonValue(QString("rating"), rating, obj, QString("QString"));
    
        

    return obj;
}

QString*
SWGAward::getProvider() {
    return provider;
}
void
SWGAward::setProvider(QString* provider) {
    this->provider = provider;
}

QString*
SWGAward::getRating() {
    return rating;
}
void
SWGAward::setRating(QString* rating) {
    this->rating = rating;
}



} /* namespace Swagger */

