/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGCityInformation.h
 * 
 * 
 */

#ifndef SWGCityInformation_H_
#define SWGCityInformation_H_

#include <QJsonObject>


#include "SWGGeolocation.h"
#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGCityInformation: public SWGObject {
public:
    SWGCityInformation();
    SWGCityInformation(QString* json);
    virtual ~SWGCityInformation();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGCityInformation* fromJson(QString &jsonString);

    QString* getCode();
    void setCode(QString* code);
QString* getGeonamesID();
    void setGeonamesID(QString* geonames_ID);
QString* getName();
    void setName(QString* name);
QString* getState();
    void setState(QString* state);
QString* getCountry();
    void setCountry(QString* country);
SWGGeolocation* getLocation();
    void setLocation(SWGGeolocation* location);
QString* getTimezone();
    void setTimezone(QString* timezone);
QString* getCurrency();
    void setCurrency(QString* currency);

private:
    QString* code;
QString* geonames_ID;
QString* name;
QString* state;
QString* country;
SWGGeolocation* location;
QString* timezone;
QString* currency;
};

} /* namespace Swagger */

#endif /* SWGCityInformation_H_ */
