/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGCarReservation.h
 * 
 * 
 */

#ifndef SWGCarReservation_H_
#define SWGCarReservation_H_

#include <QJsonObject>


#include "SWGCarReservationBookingInfo.h"
#include "SWGCompany.h"
#include "SWGVehicle.h"
#include <QList>
#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGCarReservation: public SWGObject {
public:
    SWGCarReservation();
    SWGCarReservation(QString* json);
    virtual ~SWGCarReservation();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGCarReservation* fromJson(QString &jsonString);

    QString* getId();
    void setId(QString* id);
QString* getPickUp();
    void setPickUp(QString* pick_up);
QString* getDropOff();
    void setDropOff(QString* drop_off);
SWGCompany* getProvider();
    void setProvider(SWGCompany* provider);
QString* getOrigin();
    void setOrigin(QString* origin);
SWGVehicle* getCar();
    void setCar(SWGVehicle* car);
QList<QString*>* getTravelerIds();
    void setTravelerIds(QList<QString*>* traveler_ids);
SWGCarReservationBookingInfo* getBookingInfo();
    void setBookingInfo(SWGCarReservationBookingInfo* booking_info);

private:
    QString* id;
QString* pick_up;
QString* drop_off;
SWGCompany* provider;
QString* origin;
SWGVehicle* car;
QList<QString*>* traveler_ids;
SWGCarReservationBookingInfo* booking_info;
};

} /* namespace Swagger */

#endif /* SWGCarReservation_H_ */
