/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGCarSearchResult.h
 * 
 * 
 */

#ifndef SWGCarSearchResult_H_
#define SWGCarSearchResult_H_

#include <QJsonObject>


#include "SWGCompany.h"
#include "SWGGeolocation.h"
#include "SWGVehicle.h"
#include <QList>
#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGCarSearchResult: public SWGObject {
public:
    SWGCarSearchResult();
    SWGCarSearchResult(QString* json);
    virtual ~SWGCarSearchResult();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGCarSearchResult* fromJson(QString &jsonString);

    SWGCompany* getProvider();
    void setProvider(SWGCompany* provider);
SWGGeolocation* getLocation();
    void setLocation(SWGGeolocation* location);
QString* getAirport();
    void setAirport(QString* airport);
QList<SWGVehicle*>* getCars();
    void setCars(QList<SWGVehicle*>* cars);

private:
    SWGCompany* provider;
SWGGeolocation* location;
QString* airport;
QList<SWGVehicle*>* cars;
};

} /* namespace Swagger */

#endif /* SWGCarSearchResult_H_ */
