/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGCompany.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGCompany::SWGCompany(QString* json) {
    init();
    this->fromJson(*json);
}

SWGCompany::SWGCompany() {
    init();
}

SWGCompany::~SWGCompany() {
    this->cleanup();
}

void
SWGCompany::init() {
    company_code = new QString("");
company_name = new QString("");
}

void
SWGCompany::cleanup() {
    if(company_code != NULL) {
        delete company_code;
    }
if(company_name != NULL) {
        delete company_name;
    }
}

SWGCompany*
SWGCompany::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGCompany::fromJsonObject(QJsonObject &pJson) {
    setValue(&company_code, pJson["company_code"], "QString", "QString");
setValue(&company_name, pJson["company_name"], "QString", "QString");
}

QString
SWGCompany::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGCompany::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("company_code"), company_code, obj, QString("QString"));
    
        

    
    toJsonValue(QString("company_name"), company_name, obj, QString("QString"));
    
        

    return obj;
}

QString*
SWGCompany::getCompanyCode() {
    return company_code;
}
void
SWGCompany::setCompanyCode(QString* company_code) {
    this->company_code = company_code;
}

QString*
SWGCompany::getCompanyName() {
    return company_name;
}
void
SWGCompany::setCompanyName(QString* company_name) {
    this->company_name = company_name;
}



} /* namespace Swagger */

