/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGFlightSearchSegment.h
 * 
 * 
 */

#ifndef SWGFlightSearchSegment_H_
#define SWGFlightSearchSegment_H_

#include <QJsonObject>


#include "SWGAirport.h"
#include "SWGFlightSearchBookingInfo.h"
#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGFlightSearchSegment: public SWGObject {
public:
    SWGFlightSearchSegment();
    SWGFlightSearchSegment(QString* json);
    virtual ~SWGFlightSearchSegment();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGFlightSearchSegment* fromJson(QString &jsonString);

    QString* getDepartsAt();
    void setDepartsAt(QString* departs_at);
QString* getArrivesAt();
    void setArrivesAt(QString* arrives_at);
SWGAirport* getOrigin();
    void setOrigin(SWGAirport* origin);
SWGAirport* getDestination();
    void setDestination(SWGAirport* destination);
QString* getMarketingAirline();
    void setMarketingAirline(QString* marketing_airline);
QString* getOperatingAirline();
    void setOperatingAirline(QString* operating_airline);
QString* getFlightNumber();
    void setFlightNumber(QString* flight_number);
QString* getAircraft();
    void setAircraft(QString* aircraft);
SWGFlightSearchBookingInfo* getBookingInfo();
    void setBookingInfo(SWGFlightSearchBookingInfo* booking_info);

private:
    QString* departs_at;
QString* arrives_at;
SWGAirport* origin;
SWGAirport* destination;
QString* marketing_airline;
QString* operating_airline;
QString* flight_number;
QString* aircraft;
SWGFlightSearchBookingInfo* booking_info;
};

} /* namespace Swagger */

#endif /* SWGFlightSearchSegment_H_ */
