/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGFare.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGFare::SWGFare(QString* json) {
    init();
    this->fromJson(*json);
}

SWGFare::SWGFare() {
    init();
}

SWGFare::~SWGFare() {
    this->cleanup();
}

void
SWGFare::init() {
    total_fare = new QString("");
tax = new QString("");
}

void
SWGFare::cleanup() {
    if(total_fare != NULL) {
        delete total_fare;
    }
if(tax != NULL) {
        delete tax;
    }
}

SWGFare*
SWGFare::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGFare::fromJsonObject(QJsonObject &pJson) {
    setValue(&total_fare, pJson["total_fare"], "QString", "QString");
setValue(&tax, pJson["tax"], "QString", "QString");
}

QString
SWGFare::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGFare::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("total_fare"), total_fare, obj, QString("QString"));
    
        

    
    toJsonValue(QString("tax"), tax, obj, QString("QString"));
    
        

    return obj;
}

QString*
SWGFare::getTotalFare() {
    return total_fare;
}
void
SWGFare::setTotalFare(QString* total_fare) {
    this->total_fare = total_fare;
}

QString*
SWGFare::getTax() {
    return tax;
}
void
SWGFare::setTax(QString* tax) {
    this->tax = tax;
}



} /* namespace Swagger */

