/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGFlightReservationBound.h
 * 
 * 
 */

#ifndef SWGFlightReservationBound_H_
#define SWGFlightReservationBound_H_

#include <QJsonObject>


#include "SWGFlightReservationSegment.h"
#include <QList>

#include "SWGObject.h"


namespace Swagger {

class SWGFlightReservationBound: public SWGObject {
public:
    SWGFlightReservationBound();
    SWGFlightReservationBound(QString* json);
    virtual ~SWGFlightReservationBound();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGFlightReservationBound* fromJson(QString &jsonString);

    QList<SWGFlightReservationSegment*>* getFlights();
    void setFlights(QList<SWGFlightReservationSegment*>* flights);

private:
    QList<SWGFlightReservationSegment*>* flights;
};

} /* namespace Swagger */

#endif /* SWGFlightReservationBound_H_ */
