/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGFlightReservationSegment.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGFlightReservationSegment::SWGFlightReservationSegment(QString* json) {
    init();
    this->fromJson(*json);
}

SWGFlightReservationSegment::SWGFlightReservationSegment() {
    init();
}

SWGFlightReservationSegment::~SWGFlightReservationSegment() {
    this->cleanup();
}

void
SWGFlightReservationSegment::init() {
    id = new QString("");
departs_at = new QString("");
arrives_at = new QString("");
origin = new SWGAirport();
destination = new SWGAirport();
marketing_airline = new QString("");
operating_airline = new QString("");
flight_number = new QString("");
traveler_ids = new QList<QString*>();
booking_info = new SWGFlightReservationBookingInfo();
}

void
SWGFlightReservationSegment::cleanup() {
    if(id != NULL) {
        delete id;
    }
if(departs_at != NULL) {
        delete departs_at;
    }
if(arrives_at != NULL) {
        delete arrives_at;
    }
if(origin != NULL) {
        delete origin;
    }
if(destination != NULL) {
        delete destination;
    }
if(marketing_airline != NULL) {
        delete marketing_airline;
    }
if(operating_airline != NULL) {
        delete operating_airline;
    }
if(flight_number != NULL) {
        delete flight_number;
    }
if(traveler_ids != NULL) {
        QList<QString*>* arr = traveler_ids;
        foreach(QString* o, *arr) {
            delete o;
        }
        delete traveler_ids;
    }
if(booking_info != NULL) {
        delete booking_info;
    }
}

SWGFlightReservationSegment*
SWGFlightReservationSegment::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGFlightReservationSegment::fromJsonObject(QJsonObject &pJson) {
    setValue(&id, pJson["id"], "QString", "QString");
setValue(&departs_at, pJson["departs_at"], "QString", "QString");
setValue(&arrives_at, pJson["arrives_at"], "QString", "QString");
setValue(&origin, pJson["origin"], "SWGAirport", "SWGAirport");
setValue(&destination, pJson["destination"], "SWGAirport", "SWGAirport");
setValue(&marketing_airline, pJson["marketing_airline"], "QString", "QString");
setValue(&operating_airline, pJson["operating_airline"], "QString", "QString");
setValue(&flight_number, pJson["flight_number"], "QString", "QString");
setValue(&traveler_ids, pJson["traveler_ids"], "QList", "QString");
setValue(&booking_info, pJson["booking_info"], "SWGFlightReservationBookingInfo", "SWGFlightReservationBookingInfo");
}

QString
SWGFlightReservationSegment::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGFlightReservationSegment::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("id"), id, obj, QString("QString"));
    
        

    
    toJsonValue(QString("departs_at"), departs_at, obj, QString("QString"));
    
        

    
    toJsonValue(QString("arrives_at"), arrives_at, obj, QString("QString"));
    
        

    
    toJsonValue(QString("origin"), origin, obj, QString("SWGAirport"));
    
        

    
    toJsonValue(QString("destination"), destination, obj, QString("SWGAirport"));
    
        

    
    toJsonValue(QString("marketing_airline"), marketing_airline, obj, QString("QString"));
    
        

    
    toJsonValue(QString("operating_airline"), operating_airline, obj, QString("QString"));
    
        

    
    toJsonValue(QString("flight_number"), flight_number, obj, QString("QString"));
    
        

    
    QList<QString*>* traveler_idsList = traveler_ids;
    QJsonArray traveler_idsJsonArray;
    toJsonArray((QList<void*>*)traveler_ids, &traveler_idsJsonArray, "traveler_ids", "QString");

    obj->insert("traveler_ids", traveler_idsJsonArray);
    

    
    toJsonValue(QString("booking_info"), booking_info, obj, QString("SWGFlightReservationBookingInfo"));
    
        

    return obj;
}

QString*
SWGFlightReservationSegment::getId() {
    return id;
}
void
SWGFlightReservationSegment::setId(QString* id) {
    this->id = id;
}

QString*
SWGFlightReservationSegment::getDepartsAt() {
    return departs_at;
}
void
SWGFlightReservationSegment::setDepartsAt(QString* departs_at) {
    this->departs_at = departs_at;
}

QString*
SWGFlightReservationSegment::getArrivesAt() {
    return arrives_at;
}
void
SWGFlightReservationSegment::setArrivesAt(QString* arrives_at) {
    this->arrives_at = arrives_at;
}

SWGAirport*
SWGFlightReservationSegment::getOrigin() {
    return origin;
}
void
SWGFlightReservationSegment::setOrigin(SWGAirport* origin) {
    this->origin = origin;
}

SWGAirport*
SWGFlightReservationSegment::getDestination() {
    return destination;
}
void
SWGFlightReservationSegment::setDestination(SWGAirport* destination) {
    this->destination = destination;
}

QString*
SWGFlightReservationSegment::getMarketingAirline() {
    return marketing_airline;
}
void
SWGFlightReservationSegment::setMarketingAirline(QString* marketing_airline) {
    this->marketing_airline = marketing_airline;
}

QString*
SWGFlightReservationSegment::getOperatingAirline() {
    return operating_airline;
}
void
SWGFlightReservationSegment::setOperatingAirline(QString* operating_airline) {
    this->operating_airline = operating_airline;
}

QString*
SWGFlightReservationSegment::getFlightNumber() {
    return flight_number;
}
void
SWGFlightReservationSegment::setFlightNumber(QString* flight_number) {
    this->flight_number = flight_number;
}

QList<QString*>*
SWGFlightReservationSegment::getTravelerIds() {
    return traveler_ids;
}
void
SWGFlightReservationSegment::setTravelerIds(QList<QString*>* traveler_ids) {
    this->traveler_ids = traveler_ids;
}

SWGFlightReservationBookingInfo*
SWGFlightReservationSegment::getBookingInfo() {
    return booking_info;
}
void
SWGFlightReservationSegment::setBookingInfo(SWGFlightReservationBookingInfo* booking_info) {
    this->booking_info = booking_info;
}



} /* namespace Swagger */

