/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGFlightSearchItinerary.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGFlightSearchItinerary::SWGFlightSearchItinerary(QString* json) {
    init();
    this->fromJson(*json);
}

SWGFlightSearchItinerary::SWGFlightSearchItinerary() {
    init();
}

SWGFlightSearchItinerary::~SWGFlightSearchItinerary() {
    this->cleanup();
}

void
SWGFlightSearchItinerary::init() {
    outbound = new SWGFlightSearchBound();
inbound = new SWGFlightSearchBound();
}

void
SWGFlightSearchItinerary::cleanup() {
    if(outbound != NULL) {
        delete outbound;
    }
if(inbound != NULL) {
        delete inbound;
    }
}

SWGFlightSearchItinerary*
SWGFlightSearchItinerary::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGFlightSearchItinerary::fromJsonObject(QJsonObject &pJson) {
    setValue(&outbound, pJson["outbound"], "SWGFlightSearchBound", "SWGFlightSearchBound");
setValue(&inbound, pJson["inbound"], "SWGFlightSearchBound", "SWGFlightSearchBound");
}

QString
SWGFlightSearchItinerary::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGFlightSearchItinerary::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("outbound"), outbound, obj, QString("SWGFlightSearchBound"));
    
        

    
    toJsonValue(QString("inbound"), inbound, obj, QString("SWGFlightSearchBound"));
    
        

    return obj;
}

SWGFlightSearchBound*
SWGFlightSearchItinerary::getOutbound() {
    return outbound;
}
void
SWGFlightSearchItinerary::setOutbound(SWGFlightSearchBound* outbound) {
    this->outbound = outbound;
}

SWGFlightSearchBound*
SWGFlightSearchItinerary::getInbound() {
    return inbound;
}
void
SWGFlightSearchItinerary::setInbound(SWGFlightSearchBound* inbound) {
    this->inbound = inbound;
}



} /* namespace Swagger */

