/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGFlightSearchBookingInfo.h
 * 
 * 
 */

#ifndef SWGFlightSearchBookingInfo_H_
#define SWGFlightSearchBookingInfo_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGFlightSearchBookingInfo: public SWGObject {
public:
    SWGFlightSearchBookingInfo();
    SWGFlightSearchBookingInfo(QString* json);
    virtual ~SWGFlightSearchBookingInfo();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGFlightSearchBookingInfo* fromJson(QString &jsonString);

    QString* getTravelClass();
    void setTravelClass(QString* travel_class);
QString* getCabinCode();
    void setCabinCode(QString* cabin_code);
QString* getBookingCode();
    void setBookingCode(QString* booking_code);
QString* getSeatsRemaining();
    void setSeatsRemaining(QString* seats_remaining);
QString* getFareFamily();
    void setFareFamily(QString* fare_family);
QString* getFareBasis();
    void setFareBasis(QString* fare_basis);

private:
    QString* travel_class;
QString* cabin_code;
QString* booking_code;
QString* seats_remaining;
QString* fare_family;
QString* fare_basis;
};

} /* namespace Swagger */

#endif /* SWGFlightSearchBookingInfo_H_ */
