/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGFrequentTravelerCard.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGFrequentTravelerCard::SWGFrequentTravelerCard(QString* json) {
    init();
    this->fromJson(*json);
}

SWGFrequentTravelerCard::SWGFrequentTravelerCard() {
    init();
}

SWGFrequentTravelerCard::~SWGFrequentTravelerCard() {
    this->cleanup();
}

void
SWGFrequentTravelerCard::init() {
    issuer_type = new QString("");
company_code = new QString("");
card_number = new QString("");
}

void
SWGFrequentTravelerCard::cleanup() {
    if(issuer_type != NULL) {
        delete issuer_type;
    }
if(company_code != NULL) {
        delete company_code;
    }
if(card_number != NULL) {
        delete card_number;
    }
}

SWGFrequentTravelerCard*
SWGFrequentTravelerCard::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGFrequentTravelerCard::fromJsonObject(QJsonObject &pJson) {
    setValue(&issuer_type, pJson["issuer_type"], "QString", "QString");
setValue(&company_code, pJson["company_code"], "QString", "QString");
setValue(&card_number, pJson["card_number"], "QString", "QString");
}

QString
SWGFrequentTravelerCard::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGFrequentTravelerCard::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("issuer_type"), issuer_type, obj, QString("QString"));
    
        

    
    toJsonValue(QString("company_code"), company_code, obj, QString("QString"));
    
        

    
    toJsonValue(QString("card_number"), card_number, obj, QString("QString"));
    
        

    return obj;
}

QString*
SWGFrequentTravelerCard::getIssuerType() {
    return issuer_type;
}
void
SWGFrequentTravelerCard::setIssuerType(QString* issuer_type) {
    this->issuer_type = issuer_type;
}

QString*
SWGFrequentTravelerCard::getCompanyCode() {
    return company_code;
}
void
SWGFrequentTravelerCard::setCompanyCode(QString* company_code) {
    this->company_code = company_code;
}

QString*
SWGFrequentTravelerCard::getCardNumber() {
    return card_number;
}
void
SWGFrequentTravelerCard::setCardNumber(QString* card_number) {
    this->card_number = card_number;
}



} /* namespace Swagger */

