/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGFareRestrictions.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGFareRestrictions::SWGFareRestrictions(QString* json) {
    init();
    this->fromJson(*json);
}

SWGFareRestrictions::SWGFareRestrictions() {
    init();
}

SWGFareRestrictions::~SWGFareRestrictions() {
    this->cleanup();
}

void
SWGFareRestrictions::init() {
    refundable = false;
change_penalties = false;
}

void
SWGFareRestrictions::cleanup() {
    

}

SWGFareRestrictions*
SWGFareRestrictions::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGFareRestrictions::fromJsonObject(QJsonObject &pJson) {
    setValue(&refundable, pJson["refundable"], "bool", "");
setValue(&change_penalties, pJson["change_penalties"], "bool", "");
}

QString
SWGFareRestrictions::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGFareRestrictions::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    obj->insert("refundable", QJsonValue(refundable));
obj->insert("change_penalties", QJsonValue(change_penalties));

    return obj;
}

bool
SWGFareRestrictions::getRefundable() {
    return refundable;
}
void
SWGFareRestrictions::setRefundable(bool refundable) {
    this->refundable = refundable;
}

bool
SWGFareRestrictions::getChangePenalties() {
    return change_penalties;
}
void
SWGFareRestrictions::setChangePenalties(bool change_penalties) {
    this->change_penalties = change_penalties;
}



} /* namespace Swagger */

