/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGFlightTicket.h
 * 
 * The flight itineraries with a ticket or transitional stored ticket (TST) in this reservation, and their prices.
 */

#ifndef SWGFlightTicket_H_
#define SWGFlightTicket_H_

#include <QJsonObject>


#include "SWGAmount.h"
#include "SWGFlightReservationBound.h"
#include <QList>
#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGFlightTicket: public SWGObject {
public:
    SWGFlightTicket();
    SWGFlightTicket(QString* json);
    virtual ~SWGFlightTicket();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGFlightTicket* fromJson(QString &jsonString);

    QString* getId();
    void setId(QString* id);
SWGAmount* getPrice();
    void setPrice(SWGAmount* price);
QList<QString*>* getTravelerIds();
    void setTravelerIds(QList<QString*>* traveler_ids);
QList<SWGFlightReservationBound*>* getFlightBounds();
    void setFlightBounds(QList<SWGFlightReservationBound*>* flight_bounds);

private:
    QString* id;
SWGAmount* price;
QList<QString*>* traveler_ids;
QList<SWGFlightReservationBound*>* flight_bounds;
};

} /* namespace Swagger */

#endif /* SWGFlightTicket_H_ */
