/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGFlightSearchBound.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGFlightSearchBound::SWGFlightSearchBound(QString* json) {
    init();
    this->fromJson(*json);
}

SWGFlightSearchBound::SWGFlightSearchBound() {
    init();
}

SWGFlightSearchBound::~SWGFlightSearchBound() {
    this->cleanup();
}

void
SWGFlightSearchBound::init() {
    flights = new QList<SWGFlightSearchSegment*>();
duration = new QString("");
}

void
SWGFlightSearchBound::cleanup() {
    if(flights != NULL) {
        QList<SWGFlightSearchSegment*>* arr = flights;
        foreach(SWGFlightSearchSegment* o, *arr) {
            delete o;
        }
        delete flights;
    }
if(duration != NULL) {
        delete duration;
    }
}

SWGFlightSearchBound*
SWGFlightSearchBound::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGFlightSearchBound::fromJsonObject(QJsonObject &pJson) {
    setValue(&flights, pJson["flights"], "QList", "SWGFlightSearchSegment");
setValue(&duration, pJson["duration"], "QString", "QString");
}

QString
SWGFlightSearchBound::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGFlightSearchBound::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    QList<SWGFlightSearchSegment*>* flightsList = flights;
    QJsonArray flightsJsonArray;
    toJsonArray((QList<void*>*)flights, &flightsJsonArray, "flights", "SWGFlightSearchSegment");

    obj->insert("flights", flightsJsonArray);
    

    
    toJsonValue(QString("duration"), duration, obj, QString("QString"));
    
        

    return obj;
}

QList<SWGFlightSearchSegment*>*
SWGFlightSearchBound::getFlights() {
    return flights;
}
void
SWGFlightSearchBound::setFlights(QList<SWGFlightSearchSegment*>* flights) {
    this->flights = flights;
}

QString*
SWGFlightSearchBound::getDuration() {
    return duration;
}
void
SWGFlightSearchBound::setDuration(QString* duration) {
    this->duration = duration;
}



} /* namespace Swagger */

