/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGFlightReservationBound.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGFlightReservationBound::SWGFlightReservationBound(QString* json) {
    init();
    this->fromJson(*json);
}

SWGFlightReservationBound::SWGFlightReservationBound() {
    init();
}

SWGFlightReservationBound::~SWGFlightReservationBound() {
    this->cleanup();
}

void
SWGFlightReservationBound::init() {
    flights = new QList<SWGFlightReservationSegment*>();
}

void
SWGFlightReservationBound::cleanup() {
    if(flights != NULL) {
        QList<SWGFlightReservationSegment*>* arr = flights;
        foreach(SWGFlightReservationSegment* o, *arr) {
            delete o;
        }
        delete flights;
    }
}

SWGFlightReservationBound*
SWGFlightReservationBound::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGFlightReservationBound::fromJsonObject(QJsonObject &pJson) {
    setValue(&flights, pJson["flights"], "QList", "SWGFlightReservationSegment");
}

QString
SWGFlightReservationBound::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGFlightReservationBound::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    QList<SWGFlightReservationSegment*>* flightsList = flights;
    QJsonArray flightsJsonArray;
    toJsonArray((QList<void*>*)flights, &flightsJsonArray, "flights", "SWGFlightReservationSegment");

    obj->insert("flights", flightsJsonArray);
    

    return obj;
}

QList<SWGFlightReservationSegment*>*
SWGFlightReservationBound::getFlights() {
    return flights;
}
void
SWGFlightReservationBound::setFlights(QList<SWGFlightReservationSegment*>* flights) {
    this->flights = flights;
}



} /* namespace Swagger */

