/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGHotelReservation.h
 * 
 * 
 */

#ifndef SWGHotelReservation_H_
#define SWGHotelReservation_H_

#include <QJsonObject>


#include "SWGAmount.h"
#include "SWGHotelReservationBookingInfo.h"
#include <QDate>
#include <QList>
#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGHotelReservation: public SWGObject {
public:
    SWGHotelReservation();
    SWGHotelReservation(QString* json);
    virtual ~SWGHotelReservation();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGHotelReservation* fromJson(QString &jsonString);

    QString* getId();
    void setId(QString* id);
QDate* getCheckIn();
    void setCheckIn(QDate* check_in);
QDate* getCheckOut();
    void setCheckOut(QDate* check_out);
QString* getPropertyCode();
    void setPropertyCode(QString* property_code);
QString* getPropertyName();
    void setPropertyName(QString* property_name);
SWGAmount* getTotalPrice();
    void setTotalPrice(SWGAmount* total_price);
QList<QString*>* getTravelerIds();
    void setTravelerIds(QList<QString*>* traveler_ids);
SWGHotelReservationBookingInfo* getBookingInfo();
    void setBookingInfo(SWGHotelReservationBookingInfo* booking_info);

private:
    QString* id;
QDate* check_in;
QDate* check_out;
QString* property_code;
QString* property_name;
SWGAmount* total_price;
QList<QString*>* traveler_ids;
SWGHotelReservationBookingInfo* booking_info;
};

} /* namespace Swagger */

#endif /* SWGHotelReservation_H_ */
