/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGHotelPropertyResponse.h
 * 
 * 
 */

#ifndef SWGHotelPropertyResponse_H_
#define SWGHotelPropertyResponse_H_

#include <QJsonObject>


#include "SWGAddress.h"
#include "SWGAmenity.h"
#include "SWGAmount.h"
#include "SWGAward.h"
#include "SWGContact.h"
#include "SWGGeolocation.h"
#include "SWGHotelRoom.h"
#include "SWGImage.h"
#include "SWGLink.h"
#include <QList>
#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGHotelPropertyResponse: public SWGObject {
public:
    SWGHotelPropertyResponse();
    SWGHotelPropertyResponse(QString* json);
    virtual ~SWGHotelPropertyResponse();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGHotelPropertyResponse* fromJson(QString &jsonString);

    QString* getPropertyCode();
    void setPropertyCode(QString* property_code);
QString* getPropertyName();
    void setPropertyName(QString* property_name);
SWGGeolocation* getLocation();
    void setLocation(SWGGeolocation* location);
SWGAddress* getAddress();
    void setAddress(SWGAddress* address);
SWGAmount* getTotalPrice();
    void setTotalPrice(SWGAmount* total_price);
SWGAmount* getMinDailyRate();
    void setMinDailyRate(SWGAmount* min_daily_rate);
QList<SWGContact*>* getContacts();
    void setContacts(QList<SWGContact*>* contacts);
QList<SWGAmenity*>* getAmenities();
    void setAmenities(QList<SWGAmenity*>* amenities);
QList<SWGAward*>* getAwards();
    void setAwards(QList<SWGAward*>* awards);
QList<SWGImage*>* getImages();
    void setImages(QList<SWGImage*>* images);
QList<SWGHotelRoom*>* getRooms();
    void setRooms(QList<SWGHotelRoom*>* rooms);
SWGLink* getMoreRoomsAtThisHotel();
    void setMoreRoomsAtThisHotel(SWGLink* more_rooms_at_this_hotel);

private:
    QString* property_code;
QString* property_name;
SWGGeolocation* location;
SWGAddress* address;
SWGAmount* total_price;
SWGAmount* min_daily_rate;
QList<SWGContact*>* contacts;
QList<SWGAmenity*>* amenities;
QList<SWGAward*>* awards;
QList<SWGImage*>* images;
QList<SWGHotelRoom*>* rooms;
SWGLink* more_rooms_at_this_hotel;
};

} /* namespace Swagger */

#endif /* SWGHotelPropertyResponse_H_ */
