/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGHotelRoom.h
 * 
 * 
 */

#ifndef SWGHotelRoom_H_
#define SWGHotelRoom_H_

#include <QJsonObject>


#include "SWGAmount.h"
#include "SWGPeriodRate.h"
#include "SWGRoomInfo.h"
#include <QList>
#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGHotelRoom: public SWGObject {
public:
    SWGHotelRoom();
    SWGHotelRoom(QString* json);
    virtual ~SWGHotelRoom();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGHotelRoom* fromJson(QString &jsonString);

    QString* getBookingCode();
    void setBookingCode(QString* booking_code);
QString* getRoomTypeCode();
    void setRoomTypeCode(QString* room_type_code);
QString* getRatePlanCode();
    void setRatePlanCode(QString* rate_plan_code);
SWGAmount* getTotalAmount();
    void setTotalAmount(SWGAmount* total_amount);
QList<SWGPeriodRate*>* getRates();
    void setRates(QList<SWGPeriodRate*>* rates);
QList<QString*>* getDescriptions();
    void setDescriptions(QList<QString*>* descriptions);
SWGRoomInfo* getRoomTypeInfo();
    void setRoomTypeInfo(SWGRoomInfo* room_type_info);
QString* getRateTypeCode();
    void setRateTypeCode(QString* rate_type_code);

private:
    QString* booking_code;
QString* room_type_code;
QString* rate_plan_code;
SWGAmount* total_amount;
QList<SWGPeriodRate*>* rates;
QList<QString*>* descriptions;
SWGRoomInfo* room_type_info;
QString* rate_type_code;
};

} /* namespace Swagger */

#endif /* SWGHotelRoom_H_ */
