/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGImageSize.h
 * 
 * An image size selector used in the YapQ API response. The size should correspond the the image_size parameter used during input
 */

#ifndef SWGImageSize_H_
#define SWGImageSize_H_

#include <QJsonObject>


#include "SWGImage.h"

#include "SWGObject.h"


namespace Swagger {

class SWGImageSize: public SWGObject {
public:
    SWGImageSize();
    SWGImageSize(QString* json);
    virtual ~SWGImageSize();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGImageSize* fromJson(QString &jsonString);

    SWGImage* getSmall();
    void setSmall(SWGImage* small);
SWGImage* getMedium();
    void setMedium(SWGImage* medium);
SWGImage* getLarge();
    void setLarge(SWGImage* large);
SWGImage* getHd();
    void setHd(SWGImage* hd);

private:
    SWGImage* small;
SWGImage* medium;
SWGImage* large;
SWGImage* hd;
};

} /* namespace Swagger */

#endif /* SWGImageSize_H_ */
