/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGInfant.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGInfant::SWGInfant(QString* json) {
    init();
    this->fromJson(*json);
}

SWGInfant::SWGInfant() {
    init();
}

SWGInfant::~SWGInfant() {
    this->cleanup();
}

void
SWGInfant::init() {
    last_name = new QString("");
first_name = new QString("");
date_of_birth = NULL;
}

void
SWGInfant::cleanup() {
    if(last_name != NULL) {
        delete last_name;
    }
if(first_name != NULL) {
        delete first_name;
    }
if(date_of_birth != NULL) {
        delete date_of_birth;
    }
}

SWGInfant*
SWGInfant::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGInfant::fromJsonObject(QJsonObject &pJson) {
    setValue(&last_name, pJson["last_name"], "QString", "QString");
setValue(&first_name, pJson["first_name"], "QString", "QString");
setValue(&date_of_birth, pJson["date_of_birth"], "QDate", "QDate");
}

QString
SWGInfant::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGInfant::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("last_name"), last_name, obj, QString("QString"));
    
        

    
    toJsonValue(QString("first_name"), first_name, obj, QString("QString"));
    
        

    
    toJsonValue(QString("date_of_birth"), date_of_birth, obj, QString("QDate"));
    
        

    return obj;
}

QString*
SWGInfant::getLastName() {
    return last_name;
}
void
SWGInfant::setLastName(QString* last_name) {
    this->last_name = last_name;
}

QString*
SWGInfant::getFirstName() {
    return first_name;
}
void
SWGInfant::setFirstName(QString* first_name) {
    this->first_name = first_name;
}

QDate*
SWGInfant::getDateOfBirth() {
    return date_of_birth;
}
void
SWGInfant::setDateOfBirth(QDate* date_of_birth) {
    this->date_of_birth = date_of_birth;
}



} /* namespace Swagger */

