/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGLowFareSearchResult.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGLowFareSearchResult::SWGLowFareSearchResult(QString* json) {
    init();
    this->fromJson(*json);
}

SWGLowFareSearchResult::SWGLowFareSearchResult() {
    init();
}

SWGLowFareSearchResult::~SWGLowFareSearchResult() {
    this->cleanup();
}

void
SWGLowFareSearchResult::init() {
    itineraries = new QList<SWGFlightSearchItinerary*>();
fare = new SWGFlightSearchPrice();
}

void
SWGLowFareSearchResult::cleanup() {
    if(itineraries != NULL) {
        QList<SWGFlightSearchItinerary*>* arr = itineraries;
        foreach(SWGFlightSearchItinerary* o, *arr) {
            delete o;
        }
        delete itineraries;
    }
if(fare != NULL) {
        delete fare;
    }
}

SWGLowFareSearchResult*
SWGLowFareSearchResult::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGLowFareSearchResult::fromJsonObject(QJsonObject &pJson) {
    setValue(&itineraries, pJson["itineraries"], "QList", "SWGFlightSearchItinerary");
setValue(&fare, pJson["fare"], "SWGFlightSearchPrice", "SWGFlightSearchPrice");
}

QString
SWGLowFareSearchResult::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGLowFareSearchResult::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    QList<SWGFlightSearchItinerary*>* itinerariesList = itineraries;
    QJsonArray itinerariesJsonArray;
    toJsonArray((QList<void*>*)itineraries, &itinerariesJsonArray, "itineraries", "SWGFlightSearchItinerary");

    obj->insert("itineraries", itinerariesJsonArray);
    

    
    toJsonValue(QString("fare"), fare, obj, QString("SWGFlightSearchPrice"));
    
        

    return obj;
}

QList<SWGFlightSearchItinerary*>*
SWGLowFareSearchResult::getItineraries() {
    return itineraries;
}
void
SWGLowFareSearchResult::setItineraries(QList<SWGFlightSearchItinerary*>* itineraries) {
    this->itineraries = itineraries;
}

SWGFlightSearchPrice*
SWGLowFareSearchResult::getFare() {
    return fare;
}
void
SWGLowFareSearchResult::setFare(SWGFlightSearchPrice* fare) {
    this->fare = fare;
}



} /* namespace Swagger */

