/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGLink.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGLink::SWGLink(QString* json) {
    init();
    this->fromJson(*json);
}

SWGLink::SWGLink() {
    init();
}

SWGLink::~SWGLink() {
    this->cleanup();
}

void
SWGLink::init() {
    href = new QString("");
}

void
SWGLink::cleanup() {
    if(href != NULL) {
        delete href;
    }
}

SWGLink*
SWGLink::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGLink::fromJsonObject(QJsonObject &pJson) {
    setValue(&href, pJson["href"], "QString", "QString");
}

QString
SWGLink::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGLink::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("href"), href, obj, QString("QString"));
    
        

    return obj;
}

QString*
SWGLink::getHref() {
    return href;
}
void
SWGLink::setHref(QString* href) {
    this->href = href;
}



} /* namespace Swagger */

