/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGPeriodRate.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGPeriodRate::SWGPeriodRate(QString* json) {
    init();
    this->fromJson(*json);
}

SWGPeriodRate::SWGPeriodRate() {
    init();
}

SWGPeriodRate::~SWGPeriodRate() {
    this->cleanup();
}

void
SWGPeriodRate::init() {
    start_date = NULL;
end_date = NULL;
currency = new QString("");
price = 0.0;
}

void
SWGPeriodRate::cleanup() {
    if(start_date != NULL) {
        delete start_date;
    }
if(end_date != NULL) {
        delete end_date;
    }
if(currency != NULL) {
        delete currency;
    }
if(price != NULL) {
        delete price;
    }
}

SWGPeriodRate*
SWGPeriodRate::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGPeriodRate::fromJsonObject(QJsonObject &pJson) {
    setValue(&start_date, pJson["start_date"], "QDate", "QDate");
setValue(&end_date, pJson["end_date"], "QDate", "QDate");
setValue(&currency, pJson["currency"], "QString", "QString");
setValue(&price, pJson["price"], "SWGNumber", "SWGNumber");
}

QString
SWGPeriodRate::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGPeriodRate::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("start_date"), start_date, obj, QString("QDate"));
    
        

    
    toJsonValue(QString("end_date"), end_date, obj, QString("QDate"));
    
        

    
    toJsonValue(QString("currency"), currency, obj, QString("QString"));
    
        

    
    toJsonValue(QString("price"), price, obj, QString("SWGNumber"));
    
        

    return obj;
}

QDate*
SWGPeriodRate::getStartDate() {
    return start_date;
}
void
SWGPeriodRate::setStartDate(QDate* start_date) {
    this->start_date = start_date;
}

QDate*
SWGPeriodRate::getEndDate() {
    return end_date;
}
void
SWGPeriodRate::setEndDate(QDate* end_date) {
    this->end_date = end_date;
}

QString*
SWGPeriodRate::getCurrency() {
    return currency;
}
void
SWGPeriodRate::setCurrency(QString* currency) {
    this->currency = currency;
}

SWGNumber*
SWGPeriodRate::getPrice() {
    return price;
}
void
SWGPeriodRate::setPrice(SWGNumber* price) {
    this->price = price;
}



} /* namespace Swagger */

