/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGPointOfInterestResult_grades.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGPointOfInterestResult_grades::SWGPointOfInterestResult_grades(QString* json) {
    init();
    this->fromJson(*json);
}

SWGPointOfInterestResult_grades::SWGPointOfInterestResult_grades() {
    init();
}

SWGPointOfInterestResult_grades::~SWGPointOfInterestResult_grades() {
    this->cleanup();
}

void
SWGPointOfInterestResult_grades::init() {
    yapq_grade = NULL;
city_grade = NULL;
}

void
SWGPointOfInterestResult_grades::cleanup() {
    

}

SWGPointOfInterestResult_grades*
SWGPointOfInterestResult_grades::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGPointOfInterestResult_grades::fromJsonObject(QJsonObject &pJson) {
    setValue(&yapq_grade, pJson["yapq_grade"], "qint32", "");
setValue(&city_grade, pJson["city_grade"], "qint32", "");
}

QString
SWGPointOfInterestResult_grades::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGPointOfInterestResult_grades::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    obj->insert("yapq_grade", QJsonValue(yapq_grade));
obj->insert("city_grade", QJsonValue(city_grade));

    return obj;
}

qint32
SWGPointOfInterestResult_grades::getYapqGrade() {
    return yapq_grade;
}
void
SWGPointOfInterestResult_grades::setYapqGrade(qint32 yapq_grade) {
    this->yapq_grade = yapq_grade;
}

qint32
SWGPointOfInterestResult_grades::getCityGrade() {
    return city_grade;
}
void
SWGPointOfInterestResult_grades::setCityGrade(qint32 city_grade) {
    this->city_grade = city_grade;
}



} /* namespace Swagger */

