/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGPointOfInterestDetails.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGPointOfInterestDetails::SWGPointOfInterestDetails(QString* json) {
    init();
    this->fromJson(*json);
}

SWGPointOfInterestDetails::SWGPointOfInterestDetails() {
    init();
}

SWGPointOfInterestDetails::~SWGPointOfInterestDetails() {
    this->cleanup();
}

void
SWGPointOfInterestDetails::init() {
    short_description = new QString("");
description = new QString("");
wiki_page_link = new QString("");
}

void
SWGPointOfInterestDetails::cleanup() {
    if(short_description != NULL) {
        delete short_description;
    }
if(description != NULL) {
        delete description;
    }
if(wiki_page_link != NULL) {
        delete wiki_page_link;
    }
}

SWGPointOfInterestDetails*
SWGPointOfInterestDetails::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGPointOfInterestDetails::fromJsonObject(QJsonObject &pJson) {
    setValue(&short_description, pJson["short_description"], "QString", "QString");
setValue(&description, pJson["description"], "QString", "QString");
setValue(&wiki_page_link, pJson["wiki_page_link"], "QString", "QString");
}

QString
SWGPointOfInterestDetails::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGPointOfInterestDetails::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("short_description"), short_description, obj, QString("QString"));
    
        

    
    toJsonValue(QString("description"), description, obj, QString("QString"));
    
        

    
    toJsonValue(QString("wiki_page_link"), wiki_page_link, obj, QString("QString"));
    
        

    return obj;
}

QString*
SWGPointOfInterestDetails::getShortDescription() {
    return short_description;
}
void
SWGPointOfInterestDetails::setShortDescription(QString* short_description) {
    this->short_description = short_description;
}

QString*
SWGPointOfInterestDetails::getDescription() {
    return description;
}
void
SWGPointOfInterestDetails::setDescription(QString* description) {
    this->description = description;
}

QString*
SWGPointOfInterestDetails::getWikiPageLink() {
    return wiki_page_link;
}
void
SWGPointOfInterestDetails::setWikiPageLink(QString* wiki_page_link) {
    this->wiki_page_link = wiki_page_link;
}



} /* namespace Swagger */

