/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGRoomInfo.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGRoomInfo::SWGRoomInfo(QString* json) {
    init();
    this->fromJson(*json);
}

SWGRoomInfo::SWGRoomInfo() {
    init();
}

SWGRoomInfo::~SWGRoomInfo() {
    this->cleanup();
}

void
SWGRoomInfo::init() {
    bed_type = new QString("");
number_of_beds = new QString("");
room_type = new QString("");
}

void
SWGRoomInfo::cleanup() {
    if(bed_type != NULL) {
        delete bed_type;
    }
if(number_of_beds != NULL) {
        delete number_of_beds;
    }
if(room_type != NULL) {
        delete room_type;
    }
}

SWGRoomInfo*
SWGRoomInfo::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGRoomInfo::fromJsonObject(QJsonObject &pJson) {
    setValue(&bed_type, pJson["bed_type"], "QString", "QString");
setValue(&number_of_beds, pJson["number_of_beds"], "QString", "QString");
setValue(&room_type, pJson["room_type"], "QString", "QString");
}

QString
SWGRoomInfo::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGRoomInfo::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("bed_type"), bed_type, obj, QString("QString"));
    
        

    
    toJsonValue(QString("number_of_beds"), number_of_beds, obj, QString("QString"));
    
        

    
    toJsonValue(QString("room_type"), room_type, obj, QString("QString"));
    
        

    return obj;
}

QString*
SWGRoomInfo::getBedType() {
    return bed_type;
}
void
SWGRoomInfo::setBedType(QString* bed_type) {
    this->bed_type = bed_type;
}

QString*
SWGRoomInfo::getNumberOfBeds() {
    return number_of_beds;
}
void
SWGRoomInfo::setNumberOfBeds(QString* number_of_beds) {
    this->number_of_beds = number_of_beds;
}

QString*
SWGRoomInfo::getRoomType() {
    return room_type;
}
void
SWGRoomInfo::setRoomType(QString* room_type) {
    this->room_type = room_type;
}



} /* namespace Swagger */

