/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGRestrictedRate.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGRestrictedRate::SWGRestrictedRate(QString* json) {
    init();
    this->fromJson(*json);
}

SWGRestrictedRate::SWGRestrictedRate() {
    init();
}

SWGRestrictedRate::~SWGRestrictedRate() {
    this->cleanup();
}

void
SWGRestrictedRate::init() {
    rate_code = new QString("");
rate_name = new QString("");
restrictions = new QString("");
}

void
SWGRestrictedRate::cleanup() {
    if(rate_code != NULL) {
        delete rate_code;
    }
if(rate_name != NULL) {
        delete rate_name;
    }
if(restrictions != NULL) {
        delete restrictions;
    }
}

SWGRestrictedRate*
SWGRestrictedRate::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGRestrictedRate::fromJsonObject(QJsonObject &pJson) {
    setValue(&rate_code, pJson["rate_code"], "QString", "QString");
setValue(&rate_name, pJson["rate_name"], "QString", "QString");
setValue(&restrictions, pJson["restrictions"], "QString", "QString");
}

QString
SWGRestrictedRate::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGRestrictedRate::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("rate_code"), rate_code, obj, QString("QString"));
    
        

    
    toJsonValue(QString("rate_name"), rate_name, obj, QString("QString"));
    
        

    
    toJsonValue(QString("restrictions"), restrictions, obj, QString("QString"));
    
        

    return obj;
}

QString*
SWGRestrictedRate::getRateCode() {
    return rate_code;
}
void
SWGRestrictedRate::setRateCode(QString* rate_code) {
    this->rate_code = rate_code;
}

QString*
SWGRestrictedRate::getRateName() {
    return rate_name;
}
void
SWGRestrictedRate::setRateName(QString* rate_name) {
    this->rate_name = rate_name;
}

QString*
SWGRestrictedRate::getRestrictions() {
    return restrictions;
}
void
SWGRestrictedRate::setRestrictions(QString* restrictions) {
    this->restrictions = restrictions;
}



} /* namespace Swagger */

