/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGRailService.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGRailService::SWGRailService(QString* json) {
    init();
    this->fromJson(*json);
}

SWGRailService::SWGRailService() {
    init();
}

SWGRailService::~SWGRailService() {
    this->cleanup();
}

void
SWGRailService::init() {
    destination_station_id = new QString("");
services = new QList<QString*>();
}

void
SWGRailService::cleanup() {
    if(destination_station_id != NULL) {
        delete destination_station_id;
    }
if(services != NULL) {
        QList<QString*>* arr = services;
        foreach(QString* o, *arr) {
            delete o;
        }
        delete services;
    }
}

SWGRailService*
SWGRailService::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGRailService::fromJsonObject(QJsonObject &pJson) {
    setValue(&destination_station_id, pJson["destination_station_id"], "QString", "QString");
setValue(&services, pJson["services"], "QList", "QString");
}

QString
SWGRailService::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGRailService::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("destination_station_id"), destination_station_id, obj, QString("QString"));
    
        

    
    QList<QString*>* servicesList = services;
    QJsonArray servicesJsonArray;
    toJsonArray((QList<void*>*)services, &servicesJsonArray, "services", "QString");

    obj->insert("services", servicesJsonArray);
    

    return obj;
}

QString*
SWGRailService::getDestinationStationId() {
    return destination_station_id;
}
void
SWGRailService::setDestinationStationId(QString* destination_station_id) {
    this->destination_station_id = destination_station_id;
}

QList<QString*>*
SWGRailService::getServices() {
    return services;
}
void
SWGRailService::setServices(QList<QString*>* services) {
    this->services = services;
}



} /* namespace Swagger */

