/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGRate.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGRate::SWGRate(QString* json) {
    init();
    this->fromJson(*json);
}

SWGRate::SWGRate() {
    init();
}

SWGRate::~SWGRate() {
    this->cleanup();
}

void
SWGRate::init() {
    type = new QString("");
price = new SWGAmount();
}

void
SWGRate::cleanup() {
    if(type != NULL) {
        delete type;
    }
if(price != NULL) {
        delete price;
    }
}

SWGRate*
SWGRate::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGRate::fromJsonObject(QJsonObject &pJson) {
    setValue(&type, pJson["type"], "QString", "QString");
setValue(&price, pJson["price"], "SWGAmount", "SWGAmount");
}

QString
SWGRate::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGRate::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("type"), type, obj, QString("QString"));
    
        

    
    toJsonValue(QString("price"), price, obj, QString("SWGAmount"));
    
        

    return obj;
}

QString*
SWGRate::getType() {
    return type;
}
void
SWGRate::setType(QString* type) {
    this->type = type;
}

SWGAmount*
SWGRate::getPrice() {
    return price;
}
void
SWGRate::setPrice(SWGAmount* price) {
    this->price = price;
}



} /* namespace Swagger */

