/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGRoomInfo.h
 * 
 * More detailed structured information about the room.
 */

#ifndef SWGRoomInfo_H_
#define SWGRoomInfo_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGRoomInfo: public SWGObject {
public:
    SWGRoomInfo();
    SWGRoomInfo(QString* json);
    virtual ~SWGRoomInfo();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGRoomInfo* fromJson(QString &jsonString);

    QString* getBedType();
    void setBedType(QString* bed_type);
QString* getNumberOfBeds();
    void setNumberOfBeds(QString* number_of_beds);
QString* getRoomType();
    void setRoomType(QString* room_type);

private:
    QString* bed_type;
QString* number_of_beds;
QString* room_type;
};

} /* namespace Swagger */

#endif /* SWGRoomInfo_H_ */
