/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGStation.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGStation::SWGStation(QString* json) {
    init();
    this->fromJson(*json);
}

SWGStation::SWGStation() {
    init();
}

SWGStation::~SWGStation() {
    this->cleanup();
}

void
SWGStation::init() {
    station_code = new QString("");
station_name = new QString("");
}

void
SWGStation::cleanup() {
    if(station_code != NULL) {
        delete station_code;
    }
if(station_name != NULL) {
        delete station_name;
    }
}

SWGStation*
SWGStation::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGStation::fromJsonObject(QJsonObject &pJson) {
    setValue(&station_code, pJson["station_code"], "QString", "QString");
setValue(&station_name, pJson["station_name"], "QString", "QString");
}

QString
SWGStation::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGStation::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("station_code"), station_code, obj, QString("QString"));
    
        

    
    toJsonValue(QString("station_name"), station_name, obj, QString("QString"));
    
        

    return obj;
}

QString*
SWGStation::getStationCode() {
    return station_code;
}
void
SWGStation::setStationCode(QString* station_code) {
    this->station_code = station_code;
}

QString*
SWGStation::getStationName() {
    return station_name;
}
void
SWGStation::setStationName(QString* station_name) {
    this->station_name = station_name;
}



} /* namespace Swagger */

