/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGTrainSearchItinerary.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGTrainSearchItinerary::SWGTrainSearchItinerary(QString* json) {
    init();
    this->fromJson(*json);
}

SWGTrainSearchItinerary::SWGTrainSearchItinerary() {
    init();
}

SWGTrainSearchItinerary::~SWGTrainSearchItinerary() {
    this->cleanup();
}

void
SWGTrainSearchItinerary::init() {
    trains = new QList<SWGTrainSearchSegment*>();
}

void
SWGTrainSearchItinerary::cleanup() {
    if(trains != NULL) {
        QList<SWGTrainSearchSegment*>* arr = trains;
        foreach(SWGTrainSearchSegment* o, *arr) {
            delete o;
        }
        delete trains;
    }
}

SWGTrainSearchItinerary*
SWGTrainSearchItinerary::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGTrainSearchItinerary::fromJsonObject(QJsonObject &pJson) {
    setValue(&trains, pJson["trains"], "QList", "SWGTrainSearchSegment");
}

QString
SWGTrainSearchItinerary::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGTrainSearchItinerary::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    QList<SWGTrainSearchSegment*>* trainsList = trains;
    QJsonArray trainsJsonArray;
    toJsonArray((QList<void*>*)trains, &trainsJsonArray, "trains", "SWGTrainSearchSegment");

    obj->insert("trains", trainsJsonArray);
    

    return obj;
}

QList<SWGTrainSearchSegment*>*
SWGTrainSearchItinerary::getTrains() {
    return trains;
}
void
SWGTrainSearchItinerary::setTrains(QList<SWGTrainSearchSegment*>* trains) {
    this->trains = trains;
}



} /* namespace Swagger */

