/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGTopDestinationsSearchResponse.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGTopDestinationsSearchResponse::SWGTopDestinationsSearchResponse(QString* json) {
    init();
    this->fromJson(*json);
}

SWGTopDestinationsSearchResponse::SWGTopDestinationsSearchResponse() {
    init();
}

SWGTopDestinationsSearchResponse::~SWGTopDestinationsSearchResponse() {
    this->cleanup();
}

void
SWGTopDestinationsSearchResponse::init() {
    period = new QString("");
origin = new QString("");
results = new QList<SWGTopDestinationsSearchResult*>();
}

void
SWGTopDestinationsSearchResponse::cleanup() {
    if(period != NULL) {
        delete period;
    }
if(origin != NULL) {
        delete origin;
    }
if(results != NULL) {
        QList<SWGTopDestinationsSearchResult*>* arr = results;
        foreach(SWGTopDestinationsSearchResult* o, *arr) {
            delete o;
        }
        delete results;
    }
}

SWGTopDestinationsSearchResponse*
SWGTopDestinationsSearchResponse::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGTopDestinationsSearchResponse::fromJsonObject(QJsonObject &pJson) {
    setValue(&period, pJson["period"], "QString", "QString");
setValue(&origin, pJson["origin"], "QString", "QString");
setValue(&results, pJson["results"], "QList", "SWGTopDestinationsSearchResult");
}

QString
SWGTopDestinationsSearchResponse::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGTopDestinationsSearchResponse::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("period"), period, obj, QString("QString"));
    
        

    
    toJsonValue(QString("origin"), origin, obj, QString("QString"));
    
        

    
    QList<SWGTopDestinationsSearchResult*>* resultsList = results;
    QJsonArray resultsJsonArray;
    toJsonArray((QList<void*>*)results, &resultsJsonArray, "results", "SWGTopDestinationsSearchResult");

    obj->insert("results", resultsJsonArray);
    

    return obj;
}

QString*
SWGTopDestinationsSearchResponse::getPeriod() {
    return period;
}
void
SWGTopDestinationsSearchResponse::setPeriod(QString* period) {
    this->period = period;
}

QString*
SWGTopDestinationsSearchResponse::getOrigin() {
    return origin;
}
void
SWGTopDestinationsSearchResponse::setOrigin(QString* origin) {
    this->origin = origin;
}

QList<SWGTopDestinationsSearchResult*>*
SWGTopDestinationsSearchResponse::getResults() {
    return results;
}
void
SWGTopDestinationsSearchResponse::setResults(QList<SWGTopDestinationsSearchResult*>* results) {
    this->results = results;
}



} /* namespace Swagger */

