/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGTraveler.h
 * 
 * 
 */

#ifndef SWGTraveler_H_
#define SWGTraveler_H_

#include <QJsonObject>


#include "SWGContact.h"
#include "SWGFrequentTravelerCard.h"
#include "SWGInfant.h"
#include <QDate>
#include <QList>
#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGTraveler: public SWGObject {
public:
    SWGTraveler();
    SWGTraveler(QString* json);
    virtual ~SWGTraveler();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGTraveler* fromJson(QString &jsonString);

    QString* getId();
    void setId(QString* id);
QString* getLastName();
    void setLastName(QString* last_name);
QString* getFirstName();
    void setFirstName(QString* first_name);
QString* getTravelerType();
    void setTravelerType(QString* traveler_type);
SWGInfant* getInfant();
    void setInfant(SWGInfant* infant);
QDate* getDateOfBirth();
    void setDateOfBirth(QDate* date_of_birth);
QList<SWGContact*>* getContacts();
    void setContacts(QList<SWGContact*>* contacts);
QList<SWGFrequentTravelerCard*>* getFrequentTravelerCards();
    void setFrequentTravelerCards(QList<SWGFrequentTravelerCard*>* frequent_traveler_cards);

private:
    QString* id;
QString* last_name;
QString* first_name;
QString* traveler_type;
SWGInfant* infant;
QDate* date_of_birth;
QList<SWGContact*>* contacts;
QList<SWGFrequentTravelerCard*>* frequent_traveler_cards;
};

} /* namespace Swagger */

#endif /* SWGTraveler_H_ */
