/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGTrainSearchSegment.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGTrainSearchSegment::SWGTrainSearchSegment(QString* json) {
    init();
    this->fromJson(*json);
}

SWGTrainSearchSegment::SWGTrainSearchSegment() {
    init();
}

SWGTrainSearchSegment::~SWGTrainSearchSegment() {
    this->cleanup();
}

void
SWGTrainSearchSegment::init() {
    departs_at = new QString("");
arrives_at = new QString("");
departure_station = new SWGStation();
arrival_station = new SWGAirport();
marketing_company = new QString("");
operating_company = new QString("");
train_number = new QString("");
train_type = new QString("");
prices = new QList<SWGTrainSearchPricing*>();
}

void
SWGTrainSearchSegment::cleanup() {
    if(departs_at != NULL) {
        delete departs_at;
    }
if(arrives_at != NULL) {
        delete arrives_at;
    }
if(departure_station != NULL) {
        delete departure_station;
    }
if(arrival_station != NULL) {
        delete arrival_station;
    }
if(marketing_company != NULL) {
        delete marketing_company;
    }
if(operating_company != NULL) {
        delete operating_company;
    }
if(train_number != NULL) {
        delete train_number;
    }
if(train_type != NULL) {
        delete train_type;
    }
if(prices != NULL) {
        QList<SWGTrainSearchPricing*>* arr = prices;
        foreach(SWGTrainSearchPricing* o, *arr) {
            delete o;
        }
        delete prices;
    }
}

SWGTrainSearchSegment*
SWGTrainSearchSegment::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGTrainSearchSegment::fromJsonObject(QJsonObject &pJson) {
    setValue(&departs_at, pJson["departs_at"], "QString", "QString");
setValue(&arrives_at, pJson["arrives_at"], "QString", "QString");
setValue(&departure_station, pJson["departure_station"], "SWGStation", "SWGStation");
setValue(&arrival_station, pJson["arrival_station"], "SWGAirport", "SWGAirport");
setValue(&marketing_company, pJson["marketing_company"], "QString", "QString");
setValue(&operating_company, pJson["operating_company"], "QString", "QString");
setValue(&train_number, pJson["train_number"], "QString", "QString");
setValue(&train_type, pJson["train_type"], "QString", "QString");
setValue(&prices, pJson["prices"], "QList", "SWGTrainSearchPricing");
}

QString
SWGTrainSearchSegment::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGTrainSearchSegment::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("departs_at"), departs_at, obj, QString("QString"));
    
        

    
    toJsonValue(QString("arrives_at"), arrives_at, obj, QString("QString"));
    
        

    
    toJsonValue(QString("departure_station"), departure_station, obj, QString("SWGStation"));
    
        

    
    toJsonValue(QString("arrival_station"), arrival_station, obj, QString("SWGAirport"));
    
        

    
    toJsonValue(QString("marketing_company"), marketing_company, obj, QString("QString"));
    
        

    
    toJsonValue(QString("operating_company"), operating_company, obj, QString("QString"));
    
        

    
    toJsonValue(QString("train_number"), train_number, obj, QString("QString"));
    
        

    
    toJsonValue(QString("train_type"), train_type, obj, QString("QString"));
    
        

    
    QList<SWGTrainSearchPricing*>* pricesList = prices;
    QJsonArray pricesJsonArray;
    toJsonArray((QList<void*>*)prices, &pricesJsonArray, "prices", "SWGTrainSearchPricing");

    obj->insert("prices", pricesJsonArray);
    

    return obj;
}

QString*
SWGTrainSearchSegment::getDepartsAt() {
    return departs_at;
}
void
SWGTrainSearchSegment::setDepartsAt(QString* departs_at) {
    this->departs_at = departs_at;
}

QString*
SWGTrainSearchSegment::getArrivesAt() {
    return arrives_at;
}
void
SWGTrainSearchSegment::setArrivesAt(QString* arrives_at) {
    this->arrives_at = arrives_at;
}

SWGStation*
SWGTrainSearchSegment::getDepartureStation() {
    return departure_station;
}
void
SWGTrainSearchSegment::setDepartureStation(SWGStation* departure_station) {
    this->departure_station = departure_station;
}

SWGAirport*
SWGTrainSearchSegment::getArrivalStation() {
    return arrival_station;
}
void
SWGTrainSearchSegment::setArrivalStation(SWGAirport* arrival_station) {
    this->arrival_station = arrival_station;
}

QString*
SWGTrainSearchSegment::getMarketingCompany() {
    return marketing_company;
}
void
SWGTrainSearchSegment::setMarketingCompany(QString* marketing_company) {
    this->marketing_company = marketing_company;
}

QString*
SWGTrainSearchSegment::getOperatingCompany() {
    return operating_company;
}
void
SWGTrainSearchSegment::setOperatingCompany(QString* operating_company) {
    this->operating_company = operating_company;
}

QString*
SWGTrainSearchSegment::getTrainNumber() {
    return train_number;
}
void
SWGTrainSearchSegment::setTrainNumber(QString* train_number) {
    this->train_number = train_number;
}

QString*
SWGTrainSearchSegment::getTrainType() {
    return train_type;
}
void
SWGTrainSearchSegment::setTrainType(QString* train_type) {
    this->train_type = train_type;
}

QList<SWGTrainSearchPricing*>*
SWGTrainSearchSegment::getPrices() {
    return prices;
}
void
SWGTrainSearchSegment::setPrices(QList<SWGTrainSearchPricing*>* prices) {
    this->prices = prices;
}



} /* namespace Swagger */

