/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGTravelRecordResponse.h
 * 
 * 
 */

#ifndef SWGTravelRecordResponse_H_
#define SWGTravelRecordResponse_H_

#include <QJsonObject>


#include "SWGMessage.h"
#include "SWGReservation.h"
#include "SWGTravelRecordHeader.h"
#include "SWGTraveler.h"
#include <QList>
#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGTravelRecordResponse: public SWGObject {
public:
    SWGTravelRecordResponse();
    SWGTravelRecordResponse(QString* json);
    virtual ~SWGTravelRecordResponse();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGTravelRecordResponse* fromJson(QString &jsonString);

    QString* getRecordLocator();
    void setRecordLocator(QString* record_locator);
SWGTravelRecordHeader* getHeader();
    void setHeader(SWGTravelRecordHeader* header);
QList<SWGMessage*>* getMessages();
    void setMessages(QList<SWGMessage*>* messages);
QList<SWGTraveler*>* getTravelers();
    void setTravelers(QList<SWGTraveler*>* travelers);
SWGReservation* getReservation();
    void setReservation(SWGReservation* reservation);

private:
    QString* record_locator;
SWGTravelRecordHeader* header;
QList<SWGMessage*>* messages;
QList<SWGTraveler*>* travelers;
SWGReservation* reservation;
};

} /* namespace Swagger */

#endif /* SWGTravelRecordResponse_H_ */
