/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGTopSearchesSearchResponse.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGTopSearchesSearchResponse::SWGTopSearchesSearchResponse(QString* json) {
    init();
    this->fromJson(*json);
}

SWGTopSearchesSearchResponse::SWGTopSearchesSearchResponse() {
    init();
}

SWGTopSearchesSearchResponse::~SWGTopSearchesSearchResponse() {
    this->cleanup();
}

void
SWGTopSearchesSearchResponse::init() {
    market = new QString("");
period = new QString("");
origin = new QString("");
destination = new QString("");
results = new QList<SWGTopSearchesSearchResult*>();
}

void
SWGTopSearchesSearchResponse::cleanup() {
    if(market != NULL) {
        delete market;
    }
if(period != NULL) {
        delete period;
    }
if(origin != NULL) {
        delete origin;
    }
if(destination != NULL) {
        delete destination;
    }
if(results != NULL) {
        QList<SWGTopSearchesSearchResult*>* arr = results;
        foreach(SWGTopSearchesSearchResult* o, *arr) {
            delete o;
        }
        delete results;
    }
}

SWGTopSearchesSearchResponse*
SWGTopSearchesSearchResponse::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGTopSearchesSearchResponse::fromJsonObject(QJsonObject &pJson) {
    setValue(&market, pJson["market"], "QString", "QString");
setValue(&period, pJson["period"], "QString", "QString");
setValue(&origin, pJson["origin"], "QString", "QString");
setValue(&destination, pJson["destination"], "QString", "QString");
setValue(&results, pJson["results"], "QList", "SWGTopSearchesSearchResult");
}

QString
SWGTopSearchesSearchResponse::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGTopSearchesSearchResponse::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("market"), market, obj, QString("QString"));
    
        

    
    toJsonValue(QString("period"), period, obj, QString("QString"));
    
        

    
    toJsonValue(QString("origin"), origin, obj, QString("QString"));
    
        

    
    toJsonValue(QString("destination"), destination, obj, QString("QString"));
    
        

    
    QList<SWGTopSearchesSearchResult*>* resultsList = results;
    QJsonArray resultsJsonArray;
    toJsonArray((QList<void*>*)results, &resultsJsonArray, "results", "SWGTopSearchesSearchResult");

    obj->insert("results", resultsJsonArray);
    

    return obj;
}

QString*
SWGTopSearchesSearchResponse::getMarket() {
    return market;
}
void
SWGTopSearchesSearchResponse::setMarket(QString* market) {
    this->market = market;
}

QString*
SWGTopSearchesSearchResponse::getPeriod() {
    return period;
}
void
SWGTopSearchesSearchResponse::setPeriod(QString* period) {
    this->period = period;
}

QString*
SWGTopSearchesSearchResponse::getOrigin() {
    return origin;
}
void
SWGTopSearchesSearchResponse::setOrigin(QString* origin) {
    this->origin = origin;
}

QString*
SWGTopSearchesSearchResponse::getDestination() {
    return destination;
}
void
SWGTopSearchesSearchResponse::setDestination(QString* destination) {
    this->destination = destination;
}

QList<SWGTopSearchesSearchResult*>*
SWGTopSearchesSearchResponse::getResults() {
    return results;
}
void
SWGTopSearchesSearchResponse::setResults(QList<SWGTopSearchesSearchResult*>* results) {
    this->results = results;
}



} /* namespace Swagger */

