/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGVehicleInfo.h
 * 
 * 
 */

#ifndef SWGVehicleInfo_H_
#define SWGVehicleInfo_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGVehicleInfo: public SWGObject {
public:
    SWGVehicleInfo();
    SWGVehicleInfo(QString* json);
    virtual ~SWGVehicleInfo();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGVehicleInfo* fromJson(QString &jsonString);

    QString* getAcrissCode();
    void setAcrissCode(QString* acriss_code);
QString* getCategory();
    void setCategory(QString* category);
QString* getType();
    void setType(QString* type);
QString* getTransmission();
    void setTransmission(QString* transmission);
bool getAirConditioning();
    void setAirConditioning(bool air_conditioning);
QString* getFuel();
    void setFuel(QString* fuel);

private:
    QString* acriss_code;
QString* category;
QString* type;
QString* transmission;
bool air_conditioning;
QString* fuel;
};

} /* namespace Swagger */

#endif /* SWGVehicleInfo_H_ */
