/**
 * Amadeus Travel Innovation Sandbox
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGVehicle.h
 * 
 * 
 */

#ifndef SWGVehicle_H_
#define SWGVehicle_H_

#include <QJsonObject>


#include "SWGAmount.h"
#include "SWGImage.h"
#include "SWGRate.h"
#include "SWGVehicleInfo.h"
#include <QList>

#include "SWGObject.h"


namespace Swagger {

class SWGVehicle: public SWGObject {
public:
    SWGVehicle();
    SWGVehicle(QString* json);
    virtual ~SWGVehicle();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGVehicle* fromJson(QString &jsonString);

    SWGVehicleInfo* getVehicleInfo();
    void setVehicleInfo(SWGVehicleInfo* vehicle_info);
QList<SWGRate*>* getRates();
    void setRates(QList<SWGRate*>* rates);
SWGAmount* getEstimatedTotal();
    void setEstimatedTotal(SWGAmount* estimated_total);
QList<SWGImage*>* getImages();
    void setImages(QList<SWGImage*>* images);

private:
    SWGVehicleInfo* vehicle_info;
QList<SWGRate*>* rates;
SWGAmount* estimated_total;
QList<SWGImage*>* images;
};

} /* namespace Swagger */

#endif /* SWGVehicle_H_ */
